# Generated by Django 4.2.3 on 2023-07-29 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post_StartUp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Tag_StartUp')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag_StartUp',
                'verbose_name_plural': 'Tags_StartUp',
            },
        ),
        migrations.CreateModel(
            name='PostFileContent_StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=post_StartUp.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_owner_StartUp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_StartUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lessonLink', models.URLField(blank=True, default='youtube.com', null=True, verbose_name='youtube.com')),
                ('codeSourceOfTheProject', models.URLField(blank=True, default='github.com', null=True, verbose_name='github.com')),
                ('authorOfTheVideo', models.TextField(default='The author Of The Video', max_length=50, verbose_name='authorOfTheVideo')),
                ('caption', models.TextField(max_length=1500, verbose_name='Caption_StartUp')),
                ('classCategory', models.TextField(blank=True, choices=[('Business Idea', 'Business Idea'), ('Business Plan', 'Business Plan'), ('Pitching', 'Pitching'), ('MVP/Idea Validation', 'MVP/Idea Validation'), ('Seed', 'Seed'), ('Series A', 'Series A'), ('Growth(Series B, C)', 'Growth(Series B, C)'), ('Scale(D+)', 'Scale(D+)'), ('Established expansion', 'Established expansion'), ('Maturity', 'Maturity'), ('Exit', 'Exit'), ('Marketing', 'Marketing'), ('(Co)Founders', '(Co)Founders')], null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('illustrated', models.IntegerField(default=1)),
                ('instructed', models.IntegerField(default=1)),
                ('content', models.ManyToManyField(blank=True, null=True, related_name='contents_StartUp', to='post_StartUp.postfilecontent_startup')),
                ('tagsStartUp', models.ManyToManyField(related_name='tags_StartUp', to='post_StartUp.tag_startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructed_StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_instructed_StartUp', to='post_StartUp.post_startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instructed_StartUp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Illustrated_StartUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_illustrated_StartUp', to='post_StartUp.post_startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_illustrated_StartUp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
